import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '@/styles/globals.css';
import pretendard from '@/assets/fonts/font';
import { ThemeModeScript } from "flowbite-react";
import localFont from 'next/font/local';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wedding Page HS",
  description: "Generated by create next app",
};

const pageProps = {
    ogUrl: 'https://syoonjn.github.io/wed-dev/',
    ogTitle: '황00 & 소00 결혼합니다.',
    ogDesc: 'X월 X일 X요일 낮 X시',
    ogImage: '/wed-dev/images/sample.webp',
}

console.log('pageProps');

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <head>
        <ThemeModeScript />
        <meta property="og:type" content="website" />
        <meta property="og:url" content={pageProps.ogUrl} />
        <meta property="og:title" content={pageProps.ogTitle} />
        <meta property="og:description" content={pageProps.ogDesc} />
        <meta property="og:image" content={pageProps.ogImage} />
      </head>
        <body className={pretendard.className}>{children}
        </body>
      </html>
  );
}