import pretendard from '@/assets/fonts/font';
import '@/styles/globals.css';
import { ThemeModeScript } from "flowbite-react";
import type { Metadata } from "next";
import getCouple from "./common/name";
import { formatKoreanDate } from "./common/wedDate";
import { AlertProvider } from "./context/AlertContext";
import ClientCookiesProvider from './lib/ClientCookiesProvider';
import ReactQueryProvider from "./lib/ReactQueryProvider";

const weddingDate = formatKoreanDate();
const { groomFullName, groomFirstName, brideFullName, brideFirstName } = getCouple();
export const metadata: Metadata = {
  title: `${groomFirstName} & ${brideFirstName} 결혼이야기`,
  description: "Generated by create next app",
};


const pageProps = {
  ogUrl: 'https://syoonjn.github.io/wed-dev/',
  ogTitle: `${groomFullName} & ${brideFullName} 결혼합니다`,
  ogDesc: weddingDate,
  ogImage: '/wed-dev/images/sample.webp',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content={pageProps.ogUrl} />
        <meta property="og:title" content={pageProps.ogTitle} />
        <meta property="og:description" content={`${pageProps.ogDesc}`} />
        <meta property="og:image" content={pageProps.ogImage} />
      </head>
      <body className={pretendard.className}>
        <AlertProvider>
          <ReactQueryProvider>
            <ClientCookiesProvider>
              {children}
            </ClientCookiesProvider>
          </ReactQueryProvider>
        </AlertProvider>
      </body>
    </html>
  );
}